### ISSUE TITLE
2019 Update Tracking Issue

### ISSUE THREAD

**Issue by kpfefferle** [Addepar/emberconf-schedule-2019#32]
- Content
  - [x] Update schedule content: https://emberconf.com/schedule.html #33 
  - [x] Update branding #33 
    - [x] EmberConf 2019 logo
    - [x] Addepar logo
- Housekeeping
  - [x] Revert MU file layout back to classic layout #34 
  - [x] Upgrade Ember, ember-cli #34 
- [Ember Octane](https://github.com/emberjs/ember.js/issues/17234)
  - [x] Angle bracket component invocation #35 
  - [x] Native classes (where possible) #36 
  - [x] Tracked properties #36 
  - [x] [Glimmer component API](https://github.com/pzuraq/emberjs-rfcs/blob/glimmer-components/text/0000-glimmer-components.md) #36 
  - [x] Native JavaScript modules (import something direct from NPM) #37
  - [ ] ~Incremental rendering(?)~ (not possible outside of glimmer at the moment of posting)
- Features to Retain
  - [x] PWA
  - [x] No jQuery
  - [x] Fastboot / Rehydration
  - [ ] WASM(?)
